# Задачки

- Создать "шахматную доску" на numpy:

```1 0 1 0 1
0 1 0 1 0
1 0 1 0 1
0 1 0 1 0
1 0 1 0 1```

- Создать случайный вектор и занулить три самых больших по модулю значения

- Диагональная матрица с квадратами натуральных чисел

- Змейка 

```[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]```
 
- Евклидово расстояние между вектором и всеми строчками матрицы

- Косинусное расстояние между вектором и всеми строчками матрицы. Косинусное расстояние для векторов
 

In [1]:
import numpy as np

# Первая

In [226]:
A=np.zeros((8,8),dtype=np.int16)
A[::2,::2]=1
A[1::2,1::2]=1
print(A)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Вторая

In [227]:
A=np.random.rand(10)
print A
A[A.argsort()[-3:]]=0
print A

[0.88781931 0.25829136 0.51638453 0.02768858 0.90422943 0.46691719
 0.26038847 0.8747005  0.2750904  0.83963123]
[0.         0.25829136 0.51638453 0.02768858 0.         0.46691719
 0.26038847 0.         0.2750904  0.83963123]


# Третья

In [228]:
A=np.diag(np.arange(1,8)**2)
A

array([[ 1,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0],
       [ 0,  0,  0, 16,  0,  0,  0],
       [ 0,  0,  0,  0, 25,  0,  0],
       [ 0,  0,  0,  0,  0, 36,  0],
       [ 0,  0,  0,  0,  0,  0, 49]])

# Четвертая

In [229]:
A=np.reshape(np.arange(1,26),(5,5)).T
A

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

# Пятая

In [230]:
A=np.random.randint(0,100,size=(5,5))
B=np.random.randint(0,100,size=(5,1))
np.linalg.norm(A-B.T,axis=1,ord=2)

array([ 93.00537619, 117.260394  , 125.10795338, 131.98105925,
       121.04131526])

# Шестая

In [231]:
A=np.random.randint(0,100,size=(5,5))
B=np.random.randint(0,100,size=(5,1))
#if A is a matrix
np.diagonal(1.0 - np.dot(A, B)/((np.linalg.norm(A,axis=1,ord=2) * np.linalg.norm(B,axis=0,ord=2))))
#if A is a vector

#np.diagonal(1.0 - np.dot(A.T, B)/((np.linalg.norm(A.T,axis=1,ord=2) * np.linalg.norm(B,axis=0,ord=2))))

array([0.21619823, 0.2493666 , 0.13970459, 0.44502497, 0.27107859])